import React from 'react';

export default function ReportGenerator({ jobs, stats }) {
  
  const generateReport = () => {
    const report = `
ICT WORKFORCE INTELLIGENCE REPORT
Ministry of Information, Communications and Technology
Generated: ${new Date().toLocaleDateString('en-KE')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXECUTIVE SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total ICT Opportunities Tracked: ${stats.totalJobs}
Public Service Commission Jobs: ${stats.pscJobs}
Private Sector Opportunities: ${stats.privateJobs}

TOP SKILLS IN DEMAND:
${stats.topSkills.map(([ skill, count], idx) => 
  `${idx + 1}. ${skill}: ${count} positions`
).join('\n')}

GEOGRAPHIC DISTRIBUTION:
${Object.entries(stats.byCounty)
  .sort(([,a], [,b]) => b - a)
  .slice(0, 5)
  .map(([county, count], idx) => `${idx + 1}. ${county}: ${count} jobs`)
  .join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

KEY INSIGHTS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. SKILLS GAP ANALYSIS
   - ${stats.topSkills[0]?.[0]} is the most demanded skill (${stats.topSkills[0]?.[1]} positions)
   - Recommend TVET curriculum alignment with market needs
   
2. REGIONAL DISTRIBUTION
   - ${Object.keys(stats.byCounty).length} counties have active ICT hiring
   - Consider digital hub placement in underserved regions

3. EMPLOYMENT PATHWAYS
   - PSC offers ${stats.pscJobs} permanent positions
   - Private sector provides ${stats.privateJobs} contract opportunities
   - Youth should target skills in: ${stats.topSkills.map(s => s[0]).join(', ')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

RECOMMENDATIONS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. Upskill youth in ${stats.topSkills[0]?.[0]} and ${stats.topSkills[1]?.[0]}
2. Expand digital literacy programs in counties with low job availability
3. Create public-private partnerships for internship placements
4. Review PSC ICT positions to match industry standards

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This report was generated by DevTrack - ICT Talent Pipeline Dashboard
Developed by: [Your Name], Software & Digital Products Intern
Ministry of ICT, ${new Date().getFullYear()}
    `.trim();
    
    // Create download
    const blob = new Blob([report], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ICT-Workforce-Report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };
  
  return (
    <div className="bg-white rounded-lg shadow-sm p-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-xl font-bold text-gray-900">
            📄 Generate Report
          </h2>
          <p className="text-gray-600 text-sm mt-1">
            Export workforce intelligence for Cabinet/Ministry briefings
          </p>
        </div>
        <button
          onClick={generateReport}
          className="px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 flex items-center gap-2"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Download Report
        </button>
      </div>
      
      {/* Preview */}
      <div className="mt-6 bg-gray-50 rounded-lg p-4 font-mono text-xs text-gray-700">
        <div className="font-bold">PREVIEW:</div>
        <div className="mt-2">
          ICT WORKFORCE INTELLIGENCE REPORT<br/>
          Generated: {new Date().toLocaleDateString('en-KE')}<br/>
          Total Opportunities: {stats.totalJobs}<br/>
          Top Skill: {stats.topSkills[0]?.[0] || 'N/A'}<br/>
          ...
        </div>
      </div>
    </div>
  );
}